// src/lib/client/ui/form/NumberInput.svelte
<script lang="ts">
	import { onMount, onDestroy, createEventDispatcher } from 'svelte';
	import { ChevronUp, ChevronDown } from 'lucide-svelte';

	const dispatch = createEventDispatcher<{ change: number | undefined }>();

	// Props
	export let name: string;
	export let id: string = name;
	export let value: number | undefined = undefined;
	export let min: number | undefined = undefined;
	export let max: number | undefined = undefined;
	export let step: number = 1;
	export let required: boolean = false;
	export let disabled: boolean = false;
	export let placeholder: string = '';
	export let font: 'mono' | 'sans' | undefined = undefined;
	export let compact: boolean = false;
	// Responsive: auto-switch to compact on smaller screens (< 1280px)
	export let responsive: boolean = false;
	export let onchange: ((value: number) => void) | undefined = undefined;
	export let onMinBlocked: (() => void) | undefined = undefined;
	export let onMaxBlocked: (() => void) | undefined = undefined;

	let inputValue = value === undefined || value === null ? '' : String(value);
	let isFocused = false;
	let isSmallScreen = false;
	let mediaQuery: MediaQueryList | null = null;

	onMount(() => {
		if (responsive && typeof window !== 'undefined') {
			mediaQuery = window.matchMedia('(max-width: 1279px)');
			isSmallScreen = mediaQuery.matches;
			mediaQuery.addEventListener('change', handleMediaChange);
		}
	});

	onDestroy(() => {
		if (mediaQuery) {
			mediaQuery.removeEventListener('change', handleMediaChange);
		}
	});

	function handleMediaChange(e: MediaQueryListEvent) {
		isSmallScreen = e.matches;
	}

	$: isCompact = compact || (responsive && isSmallScreen);
	$: hideButtons = responsive && isSmallScreen;
	$: fontClass = font === 'mono' ? 'font-mono' : font === 'sans' ? 'font-sans' : '';
	$: inputSizeClasses = isCompact
		? hideButtons
			? 'rounded-lg px-2.5 py-1.5 text-xs'
			: 'rounded-lg px-2.5 py-1.5 pr-7 text-xs'
		: 'rounded-xl px-3 py-2 pr-10 text-sm';
	$: buttonWidthClass = isCompact ? 'w-4' : 'w-6';
	$: iconSize = isCompact ? 10 : 12;
	$: buttonTopRadius = isCompact
		? 'rounded-tr-lg rounded-tl-none rounded-br-none rounded-bl-none'
		: 'rounded-tr-xl rounded-tl-none rounded-br-none rounded-bl-none';
	$: buttonBottomRadius = isCompact
		? 'rounded-br-lg rounded-bl-none rounded-tr-none rounded-tl-none'
		: 'rounded-br-xl rounded-bl-none rounded-tr-none rounded-tl-none';

	$: if (!isFocused) {
		inputValue = value === undefined || value === null ? '' : String(value);
	}

	function updateValue(newValue: number) {
		value = newValue;
		inputValue = String(newValue);
		onchange?.(newValue);
		dispatch('change', newValue);
	}

	// Increment/decrement handlers
	function increment() {
		const currentValue = value ?? min ?? 0;
		if (max !== undefined && currentValue >= max) {
			onMaxBlocked?.();
			return;
		}
		updateValue(currentValue + step);
	}

	function decrement() {
		const currentValue = value ?? min ?? 0;
		if (min !== undefined && currentValue <= min) {
			onMinBlocked?.();
			return;
		}
		updateValue(currentValue - step);
	}

	// Validate on input
	function handleInput(event: Event) {
		const target = event.target as HTMLInputElement;

		inputValue = target.value;

		// Allow partial input states (e.g., "-", ".", "-.")
		if (inputValue === '' || inputValue === '-' || inputValue === '.' || inputValue === '-.') {
			return;
		}

		let newValue = Number(inputValue);

		if (Number.isNaN(newValue)) {
			return;
		}

		if (min !== undefined && newValue < min) {
			newValue = min;
		}

		if (max !== undefined && newValue > max) {
			newValue = max;
		}

		updateValue(newValue);
	}

	function handleBlur() {
		isFocused = false;
		if (inputValue === '' || inputValue === '-' || inputValue === '.' || inputValue === '-.') {
			value = undefined;
			dispatch('change', undefined);
			inputValue = '';
			return;
		}

		let newValue = Number(inputValue);
		if (Number.isNaN(newValue)) {
			inputValue = value === undefined || value === null ? '' : String(value);
			return;
		}

		if (min !== undefined && newValue < min) {
			newValue = min;
		}

		if (max !== undefined && newValue > max) {
			newValue = max;
		}

		updateValue(newValue);
	}

	function handleFocus() {
		isFocused = true;
	}
</script>

<div class="relative">
	<input
		type="number"
		{id}
		{name}
		bind:value={inputValue}
		on:input={handleInput}
		on:focus={handleFocus}
		on:blur={handleBlur}
		{min}
		{max}
		{step}
		{required}
		{disabled}
		{placeholder}
		class="block w-full [appearance:textfield] border border-neutral-300 bg-white text-neutral-900 placeholder-neutral-400 transition-colors focus:border-neutral-400 focus:outline-none disabled:bg-neutral-100 disabled:text-neutral-500 dark:border-neutral-700/60 dark:bg-neutral-800/50 dark:text-neutral-50 dark:placeholder-neutral-500 dark:focus:border-neutral-600 dark:disabled:bg-neutral-800/40 dark:disabled:text-neutral-500 [&::-webkit-inner-spin-button]:appearance-none [&::-webkit-outer-spin-button]:appearance-none {inputSizeClasses} {fontClass}"
	/>

	<!-- Custom increment/decrement buttons (hidden on mobile when responsive) -->
	{#if !hideButtons}
		<div class="absolute top-0 right-0 bottom-0 flex flex-col">
			<button
				type="button"
				on:click={increment}
				{disabled}
				class="flex flex-1 {buttonWidthClass} items-center justify-center {buttonTopRadius} border border-neutral-300 bg-white text-neutral-600 transition-colors hover:bg-neutral-50 disabled:cursor-not-allowed disabled:opacity-40 dark:border-neutral-700/60 dark:bg-neutral-800/50 dark:text-neutral-300 dark:hover:bg-neutral-800"
			>
				<ChevronUp size={iconSize} />
			</button>
			<button
				type="button"
				on:click={decrement}
				{disabled}
				class="flex flex-1 {buttonWidthClass} items-center justify-center {buttonBottomRadius} border border-t-0 border-neutral-300 bg-white text-neutral-600 transition-colors hover:bg-neutral-50 disabled:cursor-not-allowed disabled:opacity-40 dark:border-neutral-700/60 dark:bg-neutral-800/50 dark:text-neutral-300 dark:hover:bg-neutral-800"
			>
				<ChevronDown size={iconSize} />
			</button>
		</div>
	{/if}
</div>

// frontend/src/components/ui/NumberInput.jsx
import React, {useState} from 'react';
import PropTypes from 'prop-types';
import {ChevronUp, ChevronDown} from 'lucide-react';

const NumberInput = ({
    value,
    onChange,
    onBlur = () => {},
    onFocus = () => {},
    className = '',
    step = 1,
    disabled = false,
    min,
    max,
    ...props
}) => {
    const [localValue, setLocalValue] = useState('');
    const [isFocused, setIsFocused] = useState(false);

    const displayValue = isFocused ? localValue : value.toString();

    const handleChange = e => {
        const input = e.target.value;
        if (input === '' || input === '-' || /^-?\d*$/.test(input)) {
            setLocalValue(input);
        }
    };

    const handleBlur = (e) => {
        setIsFocused(false);
        const numValue =
            localValue === '' || localValue === '-' ? 0 : parseInt(localValue);

        if (min !== undefined && numValue < min) {
            onChange(min);
        } else if (max !== undefined && numValue > max) {
            onChange(max);
        } else {
            onChange(numValue);
        }
        
        onBlur(e);
    };

    const handleFocus = (e) => {
        setIsFocused(true);
        setLocalValue(value.toString());
        onFocus(e);
    };

    const increment = () => {
        const newValue = value + step;
        if (max === undefined || newValue <= max) {
            onChange(newValue);
        }
    };

    const decrement = () => {
        const newValue = value - step;
        if (min === undefined || newValue >= min) {
            onChange(newValue);
        }
    };

    const handleKeyDown = e => {
        if (e.key === 'ArrowUp') {
            e.preventDefault();
            increment();
        } else if (e.key === 'ArrowDown') {
            e.preventDefault();
            decrement();
        }
    };

    const inputClasses = [
        'w-full h-8 px-2 py-1 text-sm border border-gray-700',
        'rounded-l focus:outline-none text-left',
        'bg-gray-800',
        isFocused ? 'text-blue-400' : 'text-gray-300',
        '[appearance:textfield]',
        disabled && 'opacity-50 cursor-not-allowed'
    ]
        .filter(Boolean)
        .join(' ');

    const buttonContainerClasses = [
        'inline-flex flex-col border border-l-0 border-gray-700 rounded-r overflow-hidden h-8',
        'bg-gray-800',
        disabled && 'opacity-50'
    ]
        .filter(Boolean)
        .join(' ');

    const buttonClasses = [
        'flex items-center justify-center h-1/2 px-1',
        'hover:bg-gray-700',
        isFocused ? 'text-blue-400' : 'text-gray-400',
        'hover:text-gray-200 transition-colors',
        'disabled:opacity-50 disabled:cursor-not-allowed'
    ].join(' ');

    return (
        <div className={`relative inline-flex ${className}`}>
            <input
                type='text'
                value={displayValue}
                onChange={handleChange}
                onBlur={handleBlur}
                onFocus={handleFocus}
                onKeyDown={handleKeyDown}
                disabled={disabled}
                className={inputClasses}
                {...props}
            />
            <div className={buttonContainerClasses}>
                <button
                    type='button'
                    onClick={increment}
                    disabled={disabled || (max !== undefined && value >= max)}
                    className={`${buttonClasses} border-b border-gray-700`}>
                    <ChevronUp className='h-3 w-3' />
                </button>
                <button
                    type='button'
                    onClick={decrement}
                    disabled={disabled || (min !== undefined && value <= min)}
                    className={buttonClasses}>
                    <ChevronDown className='h-3 w-3' />
                </button>
            </div>
        </div>
    );
};

NumberInput.propTypes = {
    /** Current number value */
    value: PropTypes.number.isRequired,
    /** Handler called when value changes */
    onChange: PropTypes.func.isRequired,
    /** Additional classes to apply to container */
    className: PropTypes.string,
    /** Amount to increment/decrement by */
    step: PropTypes.number,
    /** Whether the input is disabled */
    disabled: PropTypes.bool,
    /** Minimum allowed value */
    min: PropTypes.number,
    /** Maximum allowed value */
    max: PropTypes.number
};

export default NumberInput;
